build:
  environment:
    php:
      version: 8.1
      pecl_extensions:
        - memcached
  cache:
    directories:
      - vendor
      - ~/.composer
  nodes:
    coverage:
      tests:
        override:
          - php-scrutinizer-run
          -
            command: composer test
            coverage:
              file: var/cache/coverage/xml/clover.xml
              format: clover

filter:
  paths:
    - src/*

tools:
  php_analyzer:
    enabled: true
    config:
      checkstyle:
        enabled: true
        naming:
          isser_method_name: ^.*$
          utility_class_name: ^.*$
      doc_comment_fixes:
        enabled: false
      reflection_fixes:
        enabled: false
      use_statement_fixes:
        enabled: false
      simplify_boolean_return:
        enabled: true
  external_code_coverage: false
  php_code_coverage: false
  php_changetracking: true
  php_cpd: true
  php_cs_fixer: false
  php_mess_detector: true
  php_pdepend: true
  sensiolabs_security_checker: true

coding_style:
  php:
    spaces:
      before_parentheses:
        closure_definition: true
      around_operators:
        concatenation: true

checks:
  php:
    code_rating: true
    duplication: true
    remove_extra_empty_lines: true
    remove_php_closing_tag: true
    remove_trailing_whitespace: true
    fix_use_statements:
      remove_unused: true
      preserve_multiple: false
      preserve_blanklines: true
      order_alphabetically: true
    fix_php_opening_tag: true
    fix_linefeed: true
    fix_line_ending: true
    fix_identation_4spaces: true
    fix_doc_comments: true
